image: node:12.18.3

stages:
  - install
  - build
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

install-dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/


build-app:
  stage: build
  variables:
    BUILD_CONFIGURATION: 'production'
  dependencies:
    - install-dependencies
  script:
    - npm run build
  artifacts:
    expire_in: 1hr
    paths:
      - dist/

pages:
  stage: deploy
  dependencies:
    - build-app
  script:
    - mkdir public
    - mv ./dist/angular-project/* ./public
  artifacts:
    paths:
      - public
  environment:
    name: 'production'
  only:
    - branches      


